[phases.setup]
nixPkgs = ["nodejs-18_x", "ruby"]

[phases.install]
cmds = [
  "bundle install",
  "bundle exec rails assets:precompile"
]

[phases.build]
cmds = [
  "bundle exec rails db:migrate RAILS_ENV=production || true"
]

[start]
cmd = "bundle exec puma -C config/puma.rb"
