[phases.setup]
nixPkgs = ["nodejs-18_x", "ruby"]

[phases.install]
cmds = [
  "bundle install"
]

[phases.build]
cmds = [
  "bundle exec rails assets:precompile || true",
  "bundle exec rails db:migrate RAILS_ENV=production || true"
]

[start]
cmd = "bundle exec rails server -b 0.0.0.0 -p $PORT"
