services:
  - type: web
    name: paleva-backend
    env: ruby
    buildCommand: bundle install
    startCommand: cd backend && bundle exec rails db:prepare RAILS_ENV=production && bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: paleva-db
          property: connectionString
    plan: free

databases:
  - name: paleva-db
    plan: free
    databaseName: paleva_production
    user: paleva
